stages: 
  - build

build-dev: 
  stage: build
  tags:
    - shrimp-care-dev
  only: 
    - dev
  script:
    - echo "running docker stage development"
    - docker image prune -f
    - cp /root/shrimp-care/core_env/.env-development .env
    - docker compose up --build -d

build-prod: 
  stage: build
  tags:
    - shrimp-care-prod
  only: 
    - main
  script:
    - echo "running docker stage production"
    - docker image prune -f
    - cp /root/shrimp-care/core_env/.env-production .env
    - docker compose up --build -d