name: Multi Environment CI/CD Github

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: [self-hosted, shrimp-care-dev] 
    if: github.ref == 'refs/heads/dev' 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Check the current user
        run: whoami

      - name: Build for Development
        run: |
          echo "Running Docker stage development"
          docker image prune -f
          if [ -f ../../../core_env/.env-development ]; then
            echo ".env-development found, copying to .env"
            cp ../../../core_env/.env-development .env
          else
            echo ".env-development not found, please check"
            exit 1
          fi
          docker compose up --build -d

  build-prod:
    runs-on: [self-hosted, shrimp-care-prod]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build for Production
        run: |
          echo "Running Docker stage production"
          docker image prune -f
          if [ -f ../../../core_env/.env-production ]; then
            echo ".env-production found, copying to .env"
            cp ../../../core_env/.env-production .env
          else
            echo ".env-production not found, please check"
            exit 1
          fi
          docker compose up --build -d
